version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    container_name: postgres
    ports:
      - "8001:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - nginx-proxy
      - default
  # nextjs:
  #   ports:
  #     - "3000:3000"
  #   container_name: nextjs
  #   restart: always
  #   depends_on:
  #     - "postgres"
  #     - "graphql-engine"
  #   networks:
  #     - nginx-proxy
  #     - default
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/.next
  #   links:
  #     - graphql-engine
  #   env_file:
  #     - .env.production
volumes:
  db_data:
networks:
  nginx-proxy: